### PR TITLE
Fix listings showing extensionless files incorrectly, Closes #1009

### LINKED ISSUE #1009: Profile is broken (release/v5.0.0)
The databrowser seems to handle the new resource mapping incorrectly.

For example, it lists the profile card as `card$.ttl`, while this `$.ttl` suffix should not be present.

As such, when displaying the contents, it gives an error:
screen shot 2018-12-05 at 10 02 20

### PR DESCRIPTION
**Pull request by rubensworks**
Fixes #1009

### CODE REVIEW

File: test/integration/ldp-test.js [hunk 1]
```diff
@@ -324,15 +324,18 @@ describe('LDP', function () {
     })
 
     it('should ldp:contains the same files in dir', () => {
-      ldp.listContainer(path.join(__dirname, '../resources/sampleContainer/'), 'https://server.tld/resources/sampleContainer/', 'https://server.tld', '', 'text/turtle')
+      ldp.listContainer(path.join(__dirname, '../resources/sampleContainer/'), 'https://server.tld/resources/sampleContainer/', '', 'server.tld')
         .then(data => {
           fs.readdir(path.join(__dirname, '../resources/sampleContainer/'), function (err, expectedFiles) {
+            // Strip dollar extension
+            expectedFiles = expectedFiles.map(ldp.resourceMapper._removeDollarExtension)
```
Comment (RubenVerborgh) [inline test/integration/ldp-test.js]: We might not want to rely on `_` methods (but I guess okay in tests).
